'use strict';

const MAX_RACE_TIME_MS = 99999;
const DEFAULT_LANE_ORDER = [0, 1, 2];
const SINGLE_LANE = 1;
const SINGLE_LANE_ORDER = [1, 1, 1];
const DEFAULT_TIME_THRESHOLD = 40;
const DEFAULT_SPEED_THRESHOLD = 5;
const DEFAULT_LAPS = 3;
const MIN_SPLIT_TIME_MS = 1000;

module.exports = {
    MAX_RACE_TIME_MS: MAX_RACE_TIME_MS,
    DEFAULT_LANE_ORDER: DEFAULT_LANE_ORDER,
    SINGLE_LANE: SINGLE_LANE,
    SINGLE_LANE_ORDER: SINGLE_LANE_ORDER,
    DEFAULT_TIME_THRESHOLD: DEFAULT_TIME_THRESHOLD,
    DEFAULT_SPEED_THRESHOLD: DEFAULT_SPEED_THRESHOLD,
    DEFAULT_LAPS: DEFAULT_LAPS,
    MIN_SPLIT_TIME_MS: MIN_SPLIT_TIME_MS
};
